using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Slugify;

namespace Data.Models
{
  public class Seed
    {
        public static async Task SeedData(DataContext context, UserManager<AppUser> userManager)
        {
            SlugHelper helper = new SlugHelper();
            if (!userManager.Users.Any()) 
            {
                var users = new List<AppUser> 
                {
                    new AppUser{DisplayName = "Bob", UserName = "bob", Email = "bob@test.com"},
                    new AppUser{DisplayName = "Tom", UserName = "tom", Email = "tom@test.com"},
                    new AppUser{DisplayName = "Jane", UserName = "jane", Email = "jane@test.com"},

                };
                foreach (var user in users) {
                    await userManager.CreateAsync(user, "Pa$$w0rd");
                }
            }

            if (context.Posts.Any()) return;
           
            var posts = new List<Post>
            {
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester",
                    UrlSlug = helper.GenerateSlug("Example post")
                }
            };

            await context.Posts.AddRangeAsync(posts);

            await context.SaveChangesAsync();
        }
    }
}