using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace Data.Models
{
  public class Seed
    {
        public static async Task SeedData(DataContext context, UserManager<AppUser> userManager)
        {
            if (!userManager.Users.Any()) 
            {
                var users = new List<AppUser> 
                {
                    new AppUser{DisplayName = "Bob", UserName = "bob", Email = "bob@test.com"},
                    new AppUser{DisplayName = "Tom", UserName = "tom", Email = "tom@test.com"},
                    new AppUser{DisplayName = "Jane", UserName = "jane", Email = "jane@test.com"},

                };
                foreach (var user in users) {
                    await userManager.CreateAsync(user, "Pa$$w0rd");
                }
            }

            if (context.Posts.Any()) return;
            
            var categories = new List<Category>
            {
                     new Category{CategoryId = 1, CategoryName = "Programming"},
                     new Category{CategoryId = 2, CategoryName = "Architecture"},
                     new Category{CategoryId = 3, CategoryName = "Web development"},
                     new Category{CategoryId = 4, CategoryName = "Frontend"},
                     new Category{CategoryId = 5, CategoryName = "Backend"},
            };

            var posts = new List<Post>
            {
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                },
                new Post
                {
                    Title = "Example post",
                    Summary = "This is an example post",
                    Body = "This is just some post. This part should contain all the markup generated by the WYSIWIG editor.",
                    Date = DateTime.Now,
                    Author = "Tester"
                }
            };

            await context.Posts.AddRangeAsync(posts);

            await context.SaveChangesAsync();
        }
    }
}